version: '3'

services:
  news-server:
    build: .
    ports:
      - "8080:8080"  # Calibre server port
      - "5000:5000"  # Web UI port
    volumes:
      - ./library:/opt/library
      - ./recipes:/opt/recipes
      - ./users.sqlite:/opt/users.sqlite
      - ./logs:/var/log/news_server
      - ./webui_config.json:/opt/webui_config.json
    env_file:
      - .env
    restart: unless-stopped
